### ISSUE TITLE
Solutions to Exercises?

### ISSUE THREAD

**Issue by mercury04G** [gvwilson/sdxpy#312]
Are there existing solutions to exercises after each chapter, or could I contribute to them?

**Comment by gvwilson** [comment]
Thank you for offering, but I deliberately _haven't_ included solutions so that instructors can use these exercises in classes without worrying about learners looking up answers online. I may revisit that in future, but right now what I think would be most useful would be more examples: https://github.com/gvwilson/sdxpy/pulls has placeholders for some, and others are always welcome. Thanks - @gvwilson
